### PR TITLE
Fix use of tag_builder for Rails >= 5.1

### LINKED ISSUE #70: tag_options error on Rails 5.1.1
I've not dug into it yet, but I suspect that `tag_options` has been deprecated. I'm getting `undefined method 'tag_options' for #<#<Class:0x007f8d2d15d3c8>:0x007f8d2d2f6e00>` inside auto_link after upgrading from rails 5.0. This is rinku `2.0.2`.

### PR DESCRIPTION
**Pull request by watsonbox**
A slight reworking of https://github.com/vmg/rinku/pull/71 which supports both Rails 5 and Rails 5.1, as [requested](https://github.com/vmg/rinku/pull/71#issuecomment-309344471).

### CODE REVIEW

File: lib/rails_rinku.rb [hunk 1]
```diff
@@ -13,10 +13,18 @@ def rinku_auto_link(text, *args, &block)
     options.reverse_merge!(:link => :all, :html => {})
     text = h(text) unless text.html_safe?
 
+    tag_options_method = if Rails.version.starts_with?('5') && Rails.version.split('.')[1].to_i > 0
```
Comment (tbuehl) [inline lib/rails_rinku.rb]: You can just check with `Rails.version >= '5.1'`, or similar. This will also prevent the gem breaking with Rails 6 and above.

**Comment by tbuehl** [comment]
Thanks for the PR! I added a comment to simplify the Rails version check.

**Comment by watsonbox** [comment]
@tbuehl Thanks for the feedback 👍 . I kind of thought it might be better to restrict the gem itself to <= 5.1 rather than predict the future, but it's true it's more flexible like this. I updated with `Gem::Version` for the comparison though, since `"10.0.0" < "5.1"`.

**Comment by kivikakk** [comment]
Thank you! :heart:

**Comment by tbuehl** [comment]
Good catch on the `"10.0.0"` comparison. Thanks for fixing this!
